meta_product_name: "Scriber"
meta_title: "Scriber - Track your subscriptions"
meta_description: "Keep track of your subscriptions and spending"
meta_image: "scriber-ogimage.png" # should exist in `app/assets/images/`
twitter_account: "@product_twitter_account"   # required for Twitter Cards
